#!/bin/bash
# Startup script for phone 
# 1. Make permissions 755
# 2. add to "~/.config/lxsession/LXDE-pi/autostart"

# add webhook start
# add gpio script

mumble mumble://$HOSTNAME@localhost/?version=1.2.0 &

cd /home/pi/dev/project/
python phone.py &
python webhook.py &
