#!/bin/bash
# Startup script for phone 
# 1. Make permissions 755
# 2. add to "~/.config/lxsession/LXDE-pi/autostart"

# add webhook start
# add gpio script

mumble mumble://$HOSTNAME@192.168.0.1/?version=1.2.0

cd /home/pi/dev/silver-barnacle/
python phone.py &
python webhook.py &
